language: c

env:
  matrix:
    - PYTHON_VERSION=2.6
    - PYTHON_VERSION=2.7
    - PYTHON_VERSION=3.3
    - PYTHON_VERSION=3.4

before_install:

    # Install conda
    - source .continuous-integration/travis/setup_environment_$TRAVIS_OS_NAME.sh

    # Create environment
    - conda create --yes -n test python=$PYTHON_VERSION
    - source activate test

    # Make sure that interactive matplotlib backends work
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

install:
    - conda install --yes pip pytest matplotlib nose

script:
   - python setup.py install
   - cd tests
   - py.test --mpl
