language: c

sudo: false

os:
  - linux
  - windows
  - osx

env:
  global:
    - SETUP_XVFB=True
    - TOXENV='test'
    - TOXARGS='-v'
    - TOXPOSARGS=''
  matrix:
    - PYTHON_VERSION=2.7 TOXENV=py27-test-mpl15
    - PYTHON_VERSION=3.5 TOXENV=py35-test-mpl20
    - PYTHON_VERSION=3.6 TOXENV=py36-test-mpl21
    - PYTHON_VERSION=3.6 TOXENV=py36-test-mpl22
    - PYTHON_VERSION=3.7 TOXENV=py37-test-mpl30
    - PYTHON_VERSION=3.8 TOXENV=py38-test-mpl31
    - PYTHON_VERSION=3.8 TOXENV=codestyle

install:
  git clone git://github.com/astropy/ci-helpers.git;
  source ci-helpers/travis/setup_conda.sh;

script:
  - pip install tox
  - tox $TOXARGS -- $TOXPOSARGS

after_success:
  - coveralls
