language: c

os:
    - linux
    - osx

env:
  global:
    - SETUP_XVFB=True
    - CONDA_DEPENDENCIES="pytest matplotlib nose"
  matrix:
    - PYTHON_VERSION=2.6
    - PYTHON_VERSION=2.7
    - PYTHON_VERSION=3.3
    - PYTHON_VERSION=3.4

install:  

    # We use the ci-helpers package from the Astropy project to set up conda 
    # with any requested dependencies above.
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh

    - python setup.py install

script:
   - cd tests
   - py.test --mpl
