language: c

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

# This causes the artifacts of the test run (specified by ARTIFACTS_PATHS lower
# down) to be uploaded to S3. The S3 settings are set via the Travis web
# interface.
addons:
  artifacts: true

os:
    - linux

env:
  global:
    - SETUP_XVFB=True
    - CONDA_DEPENDENCIES="pytest matplotlib nose coverage"
    - PIP_DEPENDENCIES="pytest-cov coveralls"
  matrix:
    - PYTHON_VERSION=3.6 MATPLOTLIB_VERSION=2.0

    # The following build is meant to check that dependencies get set up correctly, but currently
    # the image tests fail, which should be investigated. 
    # - PYTHON_VERSION=3.5 CONDA_DEPENDENCIES="coverage freetype libpng"

install:

    # We use the ci-helpers package from the Astropy project to set up conda
    # with any requested dependencies above.
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh

    # Need to use develop instead of install to make sure coverage works
    - python setup.py develop

    # Generate a results directory name that is deterministic
    - if [[ $TRAVIS_EVENT_TYPE == pull_request ]]; then
          ARTIFACTS_PATHS="pull-request-$TRAVIS_PULL_REQUEST";
      else
          ARTIFACTS_PATHS="branch-$TRAVIS_BRANCH";
      fi

script:
   - python -c 'import pytest_mpl.plugin'
   - py.test --mpl --cov pytest_mpl tests --mpl-results-path=$ARTIFACTS_PATHS
   - python setup.py check --restructuredtext

after_success:
   - coveralls

after_failure:
  - curl -sL https://raw.githubusercontent.com/travis-ci/artifacts/master/install | bash
  - artifacts upload
